//small tables seat 1-3 people, medium 4-6, large 7-10
//each time it is reserved then decrement by 1
export default [{
    "time": "10:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "10:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "11:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "11:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "12:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "12:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "13:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "13:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "14:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "14:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "15:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "15:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "16:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "16:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "17:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "17:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "18:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "18:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "19:00",
    "small": 4,
    "medium": 4,
    "large": 4
  }, {
    "time": "19:30",
    "small": 4,
    "medium": 4,
    "large": 4
  }]